### ISSUE TITLE
html/agent.js mixes internal state updates, output and input

### ISSUE THREAD

**Issue by KristianLyng** [varnish/vagent2#25] opened 2013-01-08 19:04 UTC
Example: listVCL() updates the active vcl: button and agent.vclList, list_params() updates agent.params and the select list at the same time, paramListDiff() both calculates which params differ and print it out, saveParam() reads the param name and value directly, update_stats() both updates agent.stats and calculates req/s.... etc

This makes it:
1. Impossible to reuse code
2. Creates strong relationships between html, css and js.
3. Is just bad practice

Examples of consequences:

Listing diffs is fine, but what if we want to populate a check-box style list and offer the user to persist these non-default values?

**Comment by Dridi** [comment] 2017-04-18 16:43
ETIMEDOUT: not a bug, only bad practice. Should be fixed if persistence is implemented.

**Closed by Dridi** 2017-04-18 16:43 UTC
Labels: bug
