### ISSUE TITLE
Latest way of managing VCL names break the VAC

### ISSUE THREAD

**Issue by hugocruz** [varnish/vagent2#184] opened 2017-01-20 13:15 UTC
Testing the 4.1.2 Rc I noticed that the VCL name in Varnishadm is truncated. 
Previously could be something like 

```
test_ 58820ba00cf27d988340b974_58820ba00cf27d988340b975
```
Now it is just truncated to test_58820ba0.
This break fundamental behaviour on the VAC side. 
What is behind this decision? I couldn't find any github issue that motivated the change. 
If a VCL is being name X why "clean it up" ?

**Comment by Dridi** [comment] 2017-01-20 13:34
Because Y is better? Assigning to myself.

**Comment by Dridi** [comment] 2017-01-20 14:31
Regression test in place:

```bash
VCL_184=test_58820ba00cf27d988340b974_58820ba00cf27d988340b975
test_it_long PUT vcl/$VCL_184 "$DUMMYVCL" "VCL compiled."
test_it_long GET vcl "" ${VCL_184:0:13}
test_it_long GET vcl "" $VCL_184
```

Only the second GET is failing:

```
Test 69: Failed:  GET vcl  test_58820ba00cf27d988340b974_58820ba00cf27d988340b975: available  auto/warm          0 boot
available  auto/warm          0 vcl1484922218
available  auto/warm          0 foo
active     auto/warm          0 foo2
available  auto/warm          0 vcl1484922224
available  auto/warm          0 test_58820ba0
```

Working on a fix.

**Closed** 2017-01-20 15:03 UTC
Labels: bug
