### ISSUE TITLE
Request parser is annoyingly picky about requiring trailing '/' in the URL

### ISSUE THREAD

**Issue by daghf** [varnish/vagent2#98] opened 2013-12-05 11:55 UTC
URL parser should be more permissive in accepting URLs where the trailing / is missing, e.g. allow /param, /html, etc.

**Comment by KristianLyng** [comment] 2015-09-17 04:25
This was largely by design.Some of it might be reasonable to change though. 

The original thinking was that the real url is /foo/thing, and that /foo/ gives a list of things. /html/ has always been special historically speaking of course.

Part of the challenge is that / is just a character. Allowing /vcl causes a conflict with /vcljson for example... And imnsho / SHOULD be just an other character in http.c. 

Maybe just special-casing /html could be enough?

**Comment by KristianLyng** [comment] 2015-09-17 04:28
For /stop and /start etc, there's no trailing url component of course. This means that of the api says /foo/, then there's support for /foo/bar, but /zoo is absolute.

**Comment by KristianLyng** [comment] 2015-10-19 14:11
I've "fixed" this for /html, and I don't consider the others that grave.

Feel free to re-open if you disagree, or file issues for particular URLs, but for now I thin it is tidier to close this.

**Closed by KristianLyng** 2015-10-19 14:11 UTC
Labels: enhancement
