### ISSUE TITLE
Varnish agent crashes after some badly vcl naming,  in calls to /direct

### ISSUE THREAD

**Issue by hugocruz** [varnish/vagent2#107] opened 2014-03-14 13:35 UTC
Several calls where made to the agent trough /direct. 

After a while varnish agent crashed when you write a vcl name with characters like, '-' . 

I was using in varnishadm : ``vcl.load bogu.s /etc/varnish/default.vcl``

The dump is the following:

``Mar 14 09:49:06 precise64 varnishd[7413]: CLI telnet 127.0.0.1 45042 127.0.0.1 6082 Rd ping
Mar 14 09:49:06 precise64 varnishd[7413]: CLI telnet 127.0.0.1 45042 127.0.0.1 6082 Wr 200 PONG 1394790546 1.0
Mar 14 09:49:06 precise64 varnish-agent[8747]: send_curl (modules/vac_register.c:78): Sending VAC registration reuest: http://10.0.2.2:8080/api/rest/register
Mar 14 09:49:06 precise64 varnish-agent[8747]: http_run (modules/http.c:415): HTTPd starting on port 16085
Mar 14 09:49:06 precise64 varnish-agent[8747]: log_request (modules/http.c:277): 10.0.2.2:16099 - GET /ping
Mar 14 09:49:06 precise64 varnishd[7413]: CLI telnet 127.0.0.1 45042 127.0.0.1 6082 Rd ping
Mar 14 09:49:06 precise64 varnishd[7413]: CLI telnet 127.0.0.1 45042 127.0.0.1 6082 Wr 200 PONG 1394790546 1.0
Mar 14 09:49:06 precise64 varnish-agent[8747]: log_request (modules/http.c:277): 10.0.2.2:16355 - PUT /push/url/s:
910a80df3ebdaedcc460f86baf9ab1a
Mar 14 09:46:05 precise64 varnish-agent[8257]: log_request (modules/http.c:277): 10.0.2.2:42464 - GET /ping
Mar 14 09:46:05 precise64 varnishd[7413]: CLI telnet 127.0.0.1 45049 127.0.0.1 6082 Rd ping
Mar 14 09:46:05 precise64 varnishd[7413]: CLI telnet 127.0.0.1 45049 127.0.0.1 6082 Wr 200 PONG 1394790365 1.0
Mar 14 09:46:05 precise64 varnish-agent[8257]: log_request (modules/http.c:277): 10.0.2.2:47072 - POST /direct
Mar 14 09:46:05 precise64 varnish-agent[8257]: log_request (modules/http.c:277): 10.0.2.2:47072 - POST /direct
Mar 14 09:46:05 precise64 varnishd[7413]: CLI telnet 127.0.0.1 45049 127.0.0.1 6082 Rd vcl.load bogu.s /etc/varnish/default.vcl
Mar 14 09:46:05 precise64 varnishd[7413]: CLI telnet 127.0.0.1 45049 127.0.0.1 6082 Wr 200 VCL compiled.
Mar 14 09:46:05 precise64 kernel: [28000.309716] do_general_protection: 24 callbacks suppressed
Mar 14 09:46:05 precise64 kernel: [28000.309719] varnish-agent[8265] general protection ip:7f3fbf917805 sp:7f3fb715b320 error:0 in libc-2.15.so[7f3fbf899000+1b3000]
Mar 14 09:49:06 precise64 varnishd[7413]: CLI telnet 127.0.0.1 45042 127.0.0.1 6082 Rd auth bb807a7d8f75db1510a5c9b8e142e4bd96e75916554bf036c2b3850ce43c4ad8
Mar 14 09:49:06 precise64 varnishd[7413]: CLI telnet 127.0.0.1 45042 127.0.0.1 6082 Wr 200 -----------------------------#012Varnish Cache CLI 1.0#012-----------------------------#012Linux,3.2.0-23-generic,x86_64,-smalloc,-smalloc,-hcritbit#012varnish-3.0.5 revision 1a89b1f#012#012Type 'help' for command list.#012Type
``
I couldn't reproduce this issue, again, but the crash was evident and happened for 3 times.

**Comment by KristianLyng** [comment] 2015-11-09 16:52
Utterly unable to reproduce, after copious amounts of crud-throwing at the agent. Closing, because I'm assuming this has been fixed in an other commit.

**Closed by KristianLyng** 2015-11-09 16:52 UTC
Labels: bug
