### ISSUE TITLE
varnish-agent2 for varnish 5.1

### ISSUE THREAD

**Issue by vladbondarenko** [varnish/vagent2#192] opened 2017-06-05 11:45 UTC
tried to compile but got 
modules/vstat.c: In function ‘do_json_cb’:
modules/vstat.c:98:9: error: ‘const struct VSC_section’ has no member named ‘fantom’
  if (sec->fantom->type[0])
         ^

and so on...

How to compile vagent2 for varnish 5.1?

**Comment by Dridi** [comment] 2017-06-05 12:10
Duplicate of #187 and #188. Sorry.

**Closed by Dridi** 2017-06-05 12:10 UTC

**Comment by vladbondarenko** [comment] 2017-06-05 12:23
Let it be duplicate but dont be too burocratical. What about vagent for varnish5.1?

**Comment by Dridi** [comment] 2017-06-05 12:40
Like I said in #187, no plans for now. However we would gladly review contributions in this direction.
